# Generated by Django 2.1.7 on 2019-06-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='desc',
        ),
    ]
